[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Humboldt-WI/bads/blob/master/exercises/1_ex_python.ipynb) 

# Exercises on Python programming
We covered a lot of concepts in the first [tutorial on Python programming](https://github.com/Humboldt-WI/bads/blob/master/tutorials/1_nb_python_intro.ipynb). Solving the exercises allows you to test your familiarity with these concepts.  

## Variables, assignments, and comparisons

1. Create two variables $a$ and $b$ and assign values of $3$ and $4.5$.

In [1]:
a,b = 3,4.5
print('a =',a,';','b =',b)

a = 3 ; b = 4.5


2. Query the type of variable $a$.

In [3]:
type(a)

int

3. Check whether variable $b$ is a text variable.

In [4]:
print(isinstance(b,str))

False


4. Calculate $a^2 + \frac{1}{b}$, $\sqrt{a*b}$, and $log_2(a)$.

In [6]:
import math
print(a**2+1/b, pow(a*b,0.5), math.log2(a))

9.222222222222221 3.6742346141747673 1.584962500721156


## Matrix algebra
Create three additional variables as follows:

 $$ A = \left( \begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 10 \end{matrix} \right) \quad
  B = \left( \begin{matrix} 1 & 4 & 7 \\ 2 & 5 & 8 \\ 3 & 6 & 9 \end{matrix} \right)  \quad
  y = \left( \begin{matrix} 1 \\ 2 \\ 3 \end{matrix} \right) $$

Perform the following operations. Note that mathematical operators like `*` might not behave in the way you need it. Wasn't there a powerful library for all sorts of numerical computations including classic linear algebra?

Calculate  

  1. $a*A$

In [14]:
#The main Python package for linear algebra is the SciPy subpackage scipy.linalg which builds on NumPy
import numpy as np
import scipy.linalg as la

print('a =',a)

A = np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A =\n',A)

print('a * A =\n',a*A)

a = 3
A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
a * A =
 [[ 3  6  9]
 [12 15 18]
 [21 24 30]]


  2. $A*B$

In [17]:
print('A =\n',A)

B = np.array([[1,4,7],[2,5,8],[3,6,9]])
print('B =\n',B)

print('A * B =\n',A@B)

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
B =
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
A * B =
 [[ 14  32  50]
 [ 32  77 122]
 [ 53 128 203]]


  3. The inverse of matrix $A$ and store the result in a variable $invA$. Any ideas how to get Python to invert a matrix? Hint: NumPy is your friend.  

In [22]:
invA = la.inv(A)
print('The inverse of matrix  𝐴 is\n',invA)

The inverse of matrix  𝐴 is
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


  4. Multiply $A$ and $invA$ and verify that the result is the identity matrix (i.e. only 1s on the diagonal). You'll probably find that it isn't, because computers usually make very small rounding error when handling real numbers. The reason is interesting, but you'll have to look it up if you're interested.

In [23]:
print(A @ invA)

[[ 1.00000000e+00 -4.44089210e-16 -1.11022302e-16]
 [ 1.33226763e-15  1.00000000e+00 -2.22044605e-16]
 [ 2.22044605e-15 -2.66453526e-15  1.00000000e+00]]


  5. The transpose of matrix $B$

In [24]:
tB = B.T
print('The transpose of matrix  𝐵 is\n',tB)

The transpose of matrix  𝐵 is
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


  6. Fill the first row of matrix $B$ with ones

In [29]:
B[0,:] = [1,1,1]
print(B)

array([[1, 1, 1],
       [2, 5, 8],
       [3, 6, 9]])

  7. Calculate the ordinary least squares estimator $\beta$ (i.e. a standard regression) 
$$ \beta = (A^{\top}A)^{-1}A^{\top} y $$ Run a web search for "Python matrix transpose" to get help on how to transpose a matrix. 

In [36]:
y = np.array([1,2,3]).T
print('y =',y)
beta = la.inv(A.T @ A) @ A.T @y
print('the ordinary least squares estimator  𝛽 =',beta)

y = [1 2 3]
the ordinary least squares estimator  𝛽 = [-3.33333333e-01  6.66666667e-01 -1.15463195e-14]


## Indexing
1. Look at values of variables $A$, $B$, and $y$ from the last exercise

In [38]:
print('A =\n',A)
print('B =\n',B)
print('y =',y)

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
B =
 [[1 1 1]
 [2 5 8]
 [3 6 9]]
y = [1 2 3]


2. Access the second element in the third row of $A$ and the first element in the second row of $B$, and compute their product

In [50]:
print(A[2,1],'*',B[1,0],'=',A[2,1] * B[1,0])

8 * 2 = 16


3. Multiply the first row of $A$ and the third column of $B$

In [52]:
print(A[0,:],'*',B[:,2],'T =',A[0,:] @ B[:,2])

[1 2 3] * [1 8 9] T = 44


4. Access the elements of y that are greater than 1 (without looking up their position manually)

In [55]:
print('the elements of y that are greater than 1 are:',y[y>1])

the elements of y that are greater than 1 are: [2 3]


5. Access the elements of A in the second column, for which the values in the first column are greater or equal to 4)

In [56]:
print('the elements of A in the second column, for which the values in the first column are greater or equal to 4 is:',
      A[:,1][A[:,0]>=4])

the elements of A in the second column, for which the values in the first column are greater or equal to 4 is: [5 8]


6. Access the 4th row of A. If this returns an error message, use Google to investigate the problem and find out what went wrong.

In [1]:
print(A[3,:])

NameError: name 'A' is not defined

## Custom functions
For many statistical applications it is practical to standardize variable values. One way to standardize is *centering and scaling*. In simple words, we make the variables comparable by reducing them to the same scale.

Start with implementing a custom function. Your function should take an argument **x**. To keep things simple, we expect x to always be a numeric vector (and not text or a matrix, for example). In the body of the function, calculate the mean and standard deviation of **x**. Store the results in variables  **mu** and **std**, respectively. Then for each element in the vector, substract the mean and divide by the standard deviation.
$$ x_{new} = \frac{x-\mu}{std}$$
Make sure your functions **returns** the standardized vector (i.e., $x_new$ in the equation) as result. You might want to import `NumPy` for calculating the mean and standard deviation.

In [59]:
def custom_function(x):
    mu = np.mean(x)
    std = np.std(x)
    x_new = (x-mu)/std
    return x_new

You should always test your functions. Create a vector **a** with the elements (-100, -25, -10, 0, 10, 25, 100) and check if your function produces the correct result.     

In [60]:
a = np.array([-100, -25, -10, 0, 10, 25, 100])
custom_function(a)

array([-1.80648921, -0.4516223 , -0.18064892,  0.        ,  0.18064892,
        0.4516223 ,  1.80648921])

*Optional*: Create a vector **b** with elements ("1", "2", "3") and check the function. Let's include a simple check in the function and give feedback. Before doing any calculations, use `if()` and `type()` to check if the input is a numeric vector. There are many ways to code the condition *x is numeric* in Python. Run a quick web search and use a simple approach. If the input is not numeric, skip the computations and print a message "input not numeric".

In [131]:
from numbers import Number
b = np.array(["1", "2", "3"])

def is_numeric(x):
    return isinstance(x, Number)

def custom_function_new(x):
    if False in list(map(is_numeric,b)):
        print('input not numeric')
    else:
        mu = np.mean(b)
        std = np.std(b)
        x_new = (b-mu)/std
        return x_new

custom_function_new(b)

input not numeric


## Data structures 
Say you want to keep track of the members of the four houses of the famous Hogwarts School of Witchcraft and Wizardry. What might be a suitable data structure. We create a dictionary named **hogwarts** and use the names of the houses as keys. Then, the values associated with those keys could be any type that supports storing a set of strings, i.e., to store the names of the members. Draw on your knowledge of Python dictionaries and list to implement such a data structure. Populate the dictionary with the following data, and feel free to add more characters if you wish. 

- Gryffindor: I'm sure you know many members of that house 
- Hufflepuff: notable members include Newt Scamander, Cedric Diggory and Nymphadora Tonks
- Ravenclaw: here we've got, e.g. Luna Lovegood, Gilderoy Lockhart and Filius Flitwick
- Slytherin: Draco Malfoy, Vincent Crabbe, Gregory Goyle, and of course the one that must not be named

In [17]:
hogwarts = {'Gryffindor' : ['Harry Potter','Ron Weasley','Hermione Granger','Ginny Weasley'],
           'Hufflepuff' : ['Nymphadora Tonks','Pomona Sprout','Newton Scamander','Theseus Scamander','Cedric Diggory'],
           'Ravenclaw' : ['Luna Lovegood','Myrtle Warren','Penelope Clearwater','Cho Chang'],
           'Slytherin' : ['Tom Riddle','Draco Malfoy','Vincent Crabbe','Gregory Goyle','Pansy Parkinson']}
print(hogwarts.keys())

print(hogwarts.values())

print(hogwarts['Gryffindor'][0])

dict_keys(['Gryffindor', 'Hufflepuff', 'Ravenclaw', 'Slytherin'])
dict_values([['Harry Potter', 'Ron Weasley', 'Hermione Granger', 'Ginny Weasley'], ['Nymphadora Tonks', 'Pomona Sprout', 'Newton Scamander', 'Theseus Scamander', 'Cedric Diggory'], ['Luna Lovegood', 'Myrtle Warren', 'Penelope Clearwater', 'Cho Chang'], ['Tom Riddle', 'Draco Malfoy', 'Vincent Crabbe', 'Gregory Goyle', 'Pansy Parkinson']])
Harry Potter


Dictionaries are really useful. Still our above data structure is limited. We can only store the name of a witch or wizard. Wouldn't it be cool to be able to store more information, something like her/his favored charm, best friend, pet, etc. 

Think about how we could realize this functionality. Well, we could create yet another dictionary in which we use a witch's/wizard's name as key and as value some some other data structure in which we can store all the details we like. To our knowledge, the names of witches / wizards are unique in the Harry Potter universe, so that names could serve as (unique) keys; nerd alert. Still a dictionary of dictionaries sounds pretty complicated. In fact, the task we described above is a perfect use case of customer classes. They allow us to store any piece of information about a person at one place.

Create a custom class wizard that facilitates storing the following properties:
- First name
- Last name
- Pet
- Pet name
- Patronus shape


Also implement a method `tell_pet()`that prints an output of the following format:
*"Harry Potter's owl is called Hedwig."* 

Implement one more  method `expecto_patronum()`. Calling that method for Harry would produce the output (print):
*"A stag appears."*

In [27]:
class wizard():
    def __init__(self, First_name, Last_name, Pet, Pet_name, Patronus_shape=None):
        self.First_name = First_name
        self.Last_name = Last_name
        self.Pet = Pet
        self.Pet_name = Pet_name
        self.Patronus_shape = Patronus_shape
    
    def tell_pet(self):
        print(self.First_name, self.Last_name,"'s", self.Pet,"is called", self.Pet_name,".")
        
    def expecto_patronum(self):
        print(self.Patronus_shape, "appears.")

hogwarts['Gryffindor'][0] = wizard('Harry','Potter','owl','Hedwig','A stag')
hogwarts['Gryffindor'][0].tell_pet()
hogwarts['Gryffindor'][0].expecto_patronum()

Harry Potter 's owl is called Hedwig .
A stag appears.


Update your dictionary with schools and their members. Instead of storing a list of names as values, your new dictionary should store a list of instances of the class wizard. Note that you need to create these instances first. So you need to create an instance of class wizard for Harry, another one for Ron, Malfoy, etc. In case your knowledge of the Potter universe is a bit shaky, just invent the data you need. Just in case, [here is a ittle refresher of the expecto patronum spell](https://www.insider.com/harry-potter-characters-patronus-2018-11).

In [28]:
hogwarts['Ravenclaw'][0] = wizard('Luna','Lovegood','thestral foal','Claudius','A hare')
hogwarts['Ravenclaw'][0].tell_pet()
hogwarts['Ravenclaw'][0].expecto_patronum()

Luna Lovegood 's thestral foal is called Claudius .
A hare appears.


## Well done!!!